table Dim_Estado
	lineageTag: 05913828-f1f8-5b64-bc51-c6d9c7a7b26b

	column Abrev
		dataType: string
		lineageTag: a2456746-ff75-5160-96bb-6f4d9fdbf1bd
		summarizeBy: none
		sourceColumn: Abrev

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		dataCategory: StateOrProvince
		lineageTag: b5bda7e5-98fa-5ebb-b77e-8cfb71c9be4a
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column RegiaoCensus
		dataType: string
		lineageTag: d3332ddb-e505-5cf5-ac71-0d7f1c1198d9
		summarizeBy: none
		sourceColumn: RegiaoCensus

		annotation SummarizationSetBy = Automatic

	column 'Tier prioridade Amorim'
		dataType: string
		lineageTag: 86424517-6052-5aaf-b9c4-6c960001ed3f
		summarizeBy: none
		sourceColumn: Tier prioridade Amorim
		sortByColumn: TierOrdem

		annotation SummarizationSetBy = Automatic

	column TierOrdem
		dataType: int64
		formatString: 0
		lineageTag: 4d3d8679-66ad-57cd-b5eb-49f18d0140ee
		summarizeBy: none
		sourceColumn: TierOrdem

		annotation SummarizationSetBy = User

	column TierCor
		dataType: string
		lineageTag: c1f3d0e4-71a2-5ffa-9728-227db7a4d5b9
		summarizeBy: none
		sourceColumn: TierCor

		annotation SummarizationSetBy = Automatic

	partition Dim_Estado = m
		mode: import
		source =
				let
				    Origem = Excel.Workbook(File.Contents(CaminhoExcel), null, true),
				    Folha = Origem{[Item="Dim_Estado",Kind="Sheet"]}[Data],
				    CabecalhosPromovidos = Table.PromoteHeaders(Folha, [PromoteAllScalars=true]),
				    TiposAlterados = Table.TransformColumnTypes(CabecalhosPromovidos,{{"Abrev", type text}, {"Estado", type text}, {"RegiaoCensus", type text}, {"Tier prioridade Amorim", type text}, {"TierOrdem", Int64.Type}, {"TierCor", type text}})
				in
				    TiposAlterados

	annotation PBI_ResultType = Table
