table Facts_Market
	lineageTag: a9ca3093-8fce-5835-954f-953f2c354ec4

	measure 'Valor Mercado' = SUM(Facts_Market[Valor])
		formatString: #,0.00
		lineageTag: ce418c2e-8fb3-5082-89b6-d16d74beec76

	measure 'Quota TAM no Mercado (%)' =
			VAR Tam = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_TAM")
			VAR Total = CALCULATE(MAX(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_DESP")
			RETURN DIVIDE(Tam, Total)
		formatString: 0.0%
		lineageTag: 0ee7fa5c-bbcf-5ecb-9481-bb885ddc458a

	measure 'ABI Meses Abaixo 50' = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[Métrica] = "ABI <50 (duração)")
		formatString: 0" meses"
		lineageTag: 6cd5a207-25a4-5d19-b021-cc999315d34e

	measure 'Dodge Momentum YoY' = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[Métrica] = "Dodge Momentum (crescimento)")
		formatString: +0"%"
		lineageTag: 92b88068-bbbc-5b25-bbcc-cae02e282988

	measure 'Starts Saude ($bn)' = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[Métrica] = "Construction starts", Dim_Segmento[Segmento] = "Saúde")
		formatString: #,0.0
		lineageTag: 70969794-c9ea-5c10-9358-3825cc574977

	measure 'Ocupacao Senior (%)' = CALCULATE(AVERAGE(Facts_Market[Valor]), Dim_Metrica[Métrica] = "Taxa de ocupação", Dim_SubSegmento[SubSegmento] = "Senior Living Premium")
		formatString: 0.0"%"
		lineageTag: fbe6ed46-fc01-508c-9b75-a261ca9d56df

	measure 'KPI Seg 1' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_PIPE_P", Dim_SubSegmento[SubSegmento] = "Hotelaria — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)", Facts_Market[Data] <= TODAY()) VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_PIPE_P", Dim_SubSegmento[SubSegmento] = "Hotelaria — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)", Facts_Market[Data] = d) RETURN FORMAT(v, "#,0", "pt-PT") & " projetos (" & FORMAT(d, "mmm yyyy", "pt-PT") & ")",
			"Saúde", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_STARTS", Dim_SubSegmento[SubSegmento] = "Saúde — total", Facts_Market[Data] <= TODAY()) VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_STARTS", Dim_SubSegmento[SubSegmento] = "Saúde — total", Facts_Market[Data] = d) RETURN "$" & FORMAT(v, "#,0.0", "pt-PT") & "bn (" & FORMAT(YEAR(d), "0") & ")",
			"Residencial de Luxo", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_MKT", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total", Facts_Market[Data] <= TODAY()) VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_MKT", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total", Facts_Market[Data] = d) RETURN "$" & FORMAT(v, "#,0.0", "pt-PT") & "bn (" & FORMAT(YEAR(d), "0") & ")",
			"Adjacente", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_OCC", Dim_SubSegmento[SubSegmento] = "Senior Living Premium", Facts_Market[Data] <= TODAY()) VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_OCC", Dim_SubSegmento[SubSegmento] = "Senior Living Premium", Facts_Market[Data] = d) RETURN FORMAT(v, "#,0.0", "pt-PT") & "% (" & FORMAT(d, "mmm yyyy", "pt-PT") & ")",
			BLANK())
		lineageTag: 030a6112-f4e4-5a8c-bb31-0f312ab8b672

	measure 'KPI Seg 2' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_PIPE_Q", Dim_SubSegmento[SubSegmento] = "Hotelaria — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)", Facts_Market[Data] <= TODAY()) VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_PIPE_Q", Dim_SubSegmento[SubSegmento] = "Hotelaria — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)", Facts_Market[Data] = d) RETURN FORMAT(v, "#,0", "pt-PT") & " quartos (" & FORMAT(d, "mmm yyyy", "pt-PT") & ")",
			"Saúde", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_NOVOS", Dim_SubSegmento[SubSegmento] = "Saúde — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_NOVOS", Dim_SubSegmento[SubSegmento] = "Saúde — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)", Facts_Market[Data] = d) RETURN FORMAT(v, "#,0", "pt-PT") & " hospitais (" & FORMAT(YEAR(d), "0") & ")",
			"Residencial de Luxo", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_CAGR", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_CAGR", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total", Facts_Market[Data] = d) RETURN FORMAT(v, "#,0.0", "pt-PT") & "%/ano até 2031",
			"Adjacente", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_DEFICE", Dim_SubSegmento[SubSegmento] = "Senior Living Premium") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_DEFICE", Dim_SubSegmento[SubSegmento] = "Senior Living Premium", Facts_Market[Data] = d) RETURN FORMAT(v, "#,0", "pt-PT") & " unidades (" & FORMAT(YEAR(d), "0") & ")",
			BLANK())
		lineageTag: baa79326-137d-5306-9077-3c862f1a70db

	measure 'KPI Seg 3' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_ABRE_P", Dim_SubSegmento[SubSegmento] = "Hotelaria — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_ABRE_P", Dim_SubSegmento[SubSegmento] = "Hotelaria — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)", Facts_Market[Data] = d) RETURN FORMAT(v, "#,0", "pt-PT") & " hotéis (" & FORMAT(YEAR(d), "0") & ")",
			"Saúde", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_RENOV", Dim_SubSegmento[SubSegmento] = "Saúde — total") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_RENOV", Dim_SubSegmento[SubSegmento] = "Saúde — total", Facts_Market[Data] = d) RETURN FORMAT(v, "#,0", "pt-PT") & "% do capex (" & FORMAT(YEAR(d), "0") & ")",
			"Residencial de Luxo", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_PRICE_SF", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_PRICE_SF", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total", Facts_Market[Data] = d) RETURN "$" & FORMAT(v, "#,0", "pt-PT") & "/sqft",
			"Adjacente", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_RENDA", Dim_SubSegmento[SubSegmento] = "Senior Living Premium", Facts_Market[Data] <= TODAY()) VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_RENDA", Dim_SubSegmento[SubSegmento] = "Senior Living Premium", Facts_Market[Data] = d) RETURN "$" & FORMAT(v, "#,0", "pt-PT") & "/mês (" & FORMAT(d, "mmm yyyy", "pt-PT") & ")",
			BLANK())
		lineageTag: d3eb49ce-2896-5387-8601-2e1ed2ff55c7

	measure 'KPI Seg 4' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_DESP", Dim_SubSegmento[SubSegmento] = "Hotelaria — total") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_DESP", Dim_SubSegmento[SubSegmento] = "Hotelaria — total", Facts_Market[Data] = d) RETURN "$" & FORMAT(v, "#,0", "pt-PT") & "bn/ano (" & FORMAT(YEAR(d), "0") & ")",
			"Saúde", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_1BN", Dim_SubSegmento[SubSegmento] = "Saúde — total") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_1BN", Dim_SubSegmento[SubSegmento] = "Saúde — total", Facts_Market[Data] = d) RETURN FORMAT(v, "#,0", "pt-PT") & " projetos (" & FORMAT(YEAR(d), "0") & ")",
			"Residencial de Luxo", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_APPREC", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_APPREC", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total", Facts_Market[Data] = d) RETURN "+" & FORMAT(v, "#,0", "pt-PT") & "% em 5 anos",
			"Adjacente", VAR d = CALCULATE(MAX(Facts_Market[Data]), Dim_Metrica[MetricaID] = "M_TRANS", Dim_SubSegmento[SubSegmento] = "Senior Living Premium") VAR v = CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_TRANS", Dim_SubSegmento[SubSegmento] = "Senior Living Premium", Facts_Market[Data] = d) RETURN "$" & FORMAT(v, "#,0", "pt-PT") & "M (" & FORMAT(YEAR(d), "0") & ")",
			BLANK())
		lineageTag: ab6cfb2b-38a3-5ed3-880a-db1dc081e947

	measure 'KPI Seg 1 Titulo' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", "Pipeline hoteleiro — nacional",
			"Saúde", "Construction starts — saúde",
			"Residencial de Luxo", "Mercado residencial de luxo",
			"Adjacente", "Ocupação senior living premium",
			"Seleciona um segmento")
		lineageTag: 06c0b4d0-7144-5128-a437-81e239ac2b10

	measure 'KPI Seg 2 Titulo' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", "Pipeline em quartos",
			"Saúde", "Novos hospitais anunciados",
			"Residencial de Luxo", "Crescimento anual (CAGR)",
			"Adjacente", "Défice de unidades senior",
			"Seleciona um segmento")
		lineageTag: 52900be9-f7ee-524a-87c3-f1a4579def2e

	measure 'KPI Seg 3 Titulo' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", "Aberturas previstas",
			"Saúde", "Renovação no capex hospitalar",
			"Residencial de Luxo", "Preço médio por sq ft (Manhattan, Corcoran)",
			"Adjacente", "Renda média mensal — senior living",
			"Seleciona um segmento")
		lineageTag: 5bb7368b-9141-5398-8887-fca91dd0613b

	measure 'KPI Seg 4 Titulo' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", "Despesa anual de construção",
			"Saúde", "Mega-projetos > $1bn",
			"Residencial de Luxo", "Valorização em 5 anos",
			"Adjacente", "Volume de transações senior",
			"Seleciona um segmento")
		lineageTag: cd98deeb-8393-5b5f-af53-4b74af289389

	measure 'Serie Segmento Temporal' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_PIPE_P", Dim_SubSegmento[SubSegmento] = "Hotelaria — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)"),
			"Saúde", CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_STARTS", Dim_SubSegmento[SubSegmento] = "Saúde — total"),
			"Residencial de Luxo", CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_MKT", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total"),
			"Adjacente", CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_OCC", Dim_SubSegmento[SubSegmento] = "Senior Living Premium"),
			BLANK())
		formatString: #,0.0
		lineageTag: df948943-6ef9-5ffb-8d81-a0d4e2a68c0a

	measure 'Titulo Grafico Temporal' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", "Momentum — pipeline hoteleiro nacional (nº projetos, trimestral)",
			"Saúde", "Construction starts saúde ($bn, 2024-2030 — inclui forecast ConstructConnect)",
			"Residencial de Luxo", "Mercado residencial de luxo ($bn, 2025 → 2031)",
			"Adjacente", "Ocupação Senior Living Premium: 77,8% → 89,5% (procura estrutural)",
			"Seleciona um segmento")
		lineageTag: 20b607a7-54e6-5ea3-bf76-e31fd64aff5b

	measure 'Serie Segmento Anual' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_ABRE_P", Dim_SubSegmento[SubSegmento] = "Hotelaria — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)"),
			"Saúde", CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_NOVOS", Dim_SubSegmento[SubSegmento] = "Saúde — total", Dim_Geografia[Cidade/Área] = "Estados Unidos (nacional)"),
			"Residencial de Luxo", CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_MKT", Dim_SubSegmento[SubSegmento] = "Residencial luxo — total"),
			"Adjacente", CALCULATE(SUM(Facts_Market[Valor]), Dim_Metrica[MetricaID] = "M_DEFICE", Dim_SubSegmento[SubSegmento] = "Senior Living Premium"),
			BLANK())
		formatString: #,0
		lineageTag: 0c081eb2-2dc4-52cc-b1ff-f52f53bcecc8

	measure 'Titulo Grafico Anual' =
			VAR Seg = SELECTEDVALUE(Dim_Segmento[Segmento], "Residencial de Luxo")
			RETURN SWITCH(Seg,
			"Hotelaria", "Aberturas de hotéis por ano (2022-2027, Lodging Econometrics)",
			"Saúde", "Novos hospitais anunciados (2025, nacional — ConstructConnect)",
			"Residencial de Luxo", "Mercado residencial de luxo por ano ($bn, Mordor)",
			"Adjacente", "Défice de senior housing — 806 mil unidades até 2030 (nº)",
			"Seleciona um segmento")
		lineageTag: a21fabe3-5c0d-5972-b83e-4500db051a9e

	column ID
		dataType: string
		lineageTag: 91f0b923-1eb0-5013-b7e0-49b52d356ee3
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		lineageTag: 23ff8127-5dd5-563b-8d79-d270f50a94f3
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: b1869c1e-5583-584f-802f-6131da678143
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Periodo
		dataType: string
		lineageTag: 785e43fb-0372-5203-9a9e-a50fe9a74033
		summarizeBy: none
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

	column SegmentoID
		dataType: string
		lineageTag: 18c49d87-5cfa-516b-be71-7cb96244adfb
		summarizeBy: none
		sourceColumn: SegmentoID

		annotation SummarizationSetBy = Automatic

	column SubSegmentoID
		dataType: string
		lineageTag: 95d39238-cb15-5f05-aa3d-91f949aeee5d
		summarizeBy: none
		sourceColumn: SubSegmentoID

		annotation SummarizationSetBy = Automatic

	column GeografiaID
		dataType: string
		lineageTag: 571e10ad-1b56-59ba-b4d5-79f0fede938b
		summarizeBy: none
		sourceColumn: GeografiaID

		annotation SummarizationSetBy = Automatic

	column MetricaID
		dataType: string
		lineageTag: 45b98706-3bd2-540e-ace3-921d17394f7d
		summarizeBy: none
		sourceColumn: MetricaID

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: 868590d5-7724-51ec-9f31-e76457c3af11
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: b664a1fa-065b-5d9f-b01f-7ba7a726b94d
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column FonteID
		dataType: string
		lineageTag: 474306ef-815e-5589-bca0-2421463d931a
		summarizeBy: none
		sourceColumn: FonteID

		annotation SummarizationSetBy = Automatic

	column Nota
		dataType: string
		lineageTag: db4786b3-72df-5171-9695-ce366d703725
		summarizeBy: none
		sourceColumn: Nota

		annotation SummarizationSetBy = Automatic

	partition Facts_Market = m
		mode: import
		source =
				let
				    Origem = Excel.Workbook(File.Contents(CaminhoExcel), null, true),
				    Folha = Origem{[Item="Facts_Market",Kind="Sheet"]}[Data],
				    CabecalhosPromovidos = Table.PromoteHeaders(Folha, [PromoteAllScalars=true]),
				    TiposAlterados = Table.TransformColumnTypes(CabecalhosPromovidos,{{"ID", type text}, {"Data", type datetime}, {"Ano", Int64.Type}, {"Periodo", type text}, {"SegmentoID", type text}, {"SubSegmentoID", type text}, {"GeografiaID", type text}, {"MetricaID", type text}, {"Valor", type number}, {"Unidade", type text}, {"FonteID", type text}, {"Nota", type text}})
				in
				    TiposAlterados

	annotation PBI_ResultType = Table
